#!/usr/bin/perl -w -- 
#
# generated by wxGlade 0.9.4 on Thu Mar 16 03:56:04 2023
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MainFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;

    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = "ACX Sync"         unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    $style = wxDEFAULT_FRAME_STYLE unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );

    $self->{sizer} = Wx::FlexGridSizer->new(3, 2, 10, 5);

    $self->set_file_input('_getVideoFile', 'Get Video file');
    $self->set_file_input('_getAudioFile', 'Get Audio file');

    $self->set_input_text('_outputFileName', 'Output file:',    100, '~/output.mp4');
    $self->set_input_text('_silenceLength',  'Silence lenght (sec):', 100, '5.0');

    $self->set_action_btn('_doSync', 'Sync!');

    $self->SetSizer($self->{sizer});
    $self->Layout();

    return $self;

}

sub set_action_btn {
    my ($self, $name, $label) = @_;

    my $button = 'button' . $name;

    $self->{$button} = Wx::Button->new($self, wxID_ANY, $label);

    $self->{sizer}->Add($self->{$button}, 0, wxALIGN_RIGHT, 0);

    $self->set_btn_event($name);
}

sub set_file_input {
    my ($self, $name, $label) = @_;

    my $text   = 'text' . $name;
    my $button = 'button' . $name;

    $self->{$button} = Wx::Button->new($self, wxID_ANY, $label);

    $self->{$text} = Wx::TextCtrl->new($self, wxID_ANY, '');
    $self->{$text}->SetMinSize(Wx::Size->new(250, 34));

    $self->{sizer}->Add($self->{$text},   0, 0, 0);
    $self->{sizer}->Add($self->{$button}, 0, 0, 0);

    $self->set_btn_event( $name );
}

sub set_input_text {
    my ($self, $name, $label, $size, $default) = @_;

    my $text   = 'text'  . $name;
    my $static = 'label' . $name;

    $self->{$static} = Wx::StaticText->new($self, wxID_ANY, $label);

    $self->{$text} = Wx::TextCtrl->new($self, wxID_ANY, $default);
    $self->{$text}->SetMinSize(Wx::Size->new($size, 34));

    $self->{sizer}->Add($self->{$static}, 0, wxALIGN_CENTER_VERTICAL|wxALIGN_RIGHT, 0);
    $self->{sizer}->Add($self->{$text}, 0, 0, 0);

}

sub set_btn_event {
    my ($self, $event) = @_;

    Wx::Event::EVT_BUTTON($self, $self->{'button' . $event}->GetId, $self->can( $event ));
}

sub _doSync {
    my ($self, $event) = @_;

    $event->Skip;
}

sub _getVideoFile {
    my ($self, $event) = @_;

    $self->_getFile( 'text_getVideoFile', 'Video file', '*.*', '~/' );
}

sub _getAudioFile {
    my ($self, $event) = @_;

    $self->_getFile( 'text_getAudioFile', 'Audio file', '*.*', '~/' );
}

sub _getFile {
    my ($self, $field, $caption, $wildcard, $defaultDir) = @_;

    my $fileDialog = Wx::FileDialog->new(
        $self,
        $caption,
        $defaultDir,
        '',
        $wildcard,
        wxFD_OPEN
    );

    my $status = $fileDialog->ShowModal();

    my $dir  = $fileDialog->GetDirectory();
    my $file = $fileDialog->GetFilename();

    $self->{ $field }->Clear();
    $self->{ $field }->WriteText($dir . '/' . $file);
}

1;

package ACXSync;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MainFrame->new();

    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}

package main;

unless(caller){
    my $acx = ACXSync->new();
    $acx->MainLoop();
}
