#!/bin/bash

# Plays video file with realtime timestamp
# Usage:
#       ./ff_tplay.sh video.mp4

ffplay -i "$1" -vf "drawtext=text='timestamp: %{pts \: hms}':fontsize=72:r=60:x=(w-tw)/2:y=h-(2*lh):fontcolor=white:box=1:boxcolor=0x00000099"